// docs/module-template/components/vue/ExampleComponent.vue
<template>
  <div class="p-4 border border-secondary rounded-lg">
    <h2 class="text-xl font-bold text-accent mb-2">{{ title }}</h2>
    <div class="text-gray-300">
      <slot>This is an example component from a scaffold-xrp module.</slot>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * Example Vue component for scaffold-xrp module
 */
interface Props {
  title?: string;
}

withDefaults(defineProps<Props>(), {
  title: 'Example Module',
});
</script>

// docs/module-template/components/react/ExampleComponent.tsx
import React from 'react';

interface ExampleComponentProps {
  title?: string;
  children?: React.ReactNode;
}

/**
 * Example React component for scaffold-xrp module
 */
export function ExampleComponent({ title = 'Example Module', children }: ExampleComponentProps) {
  return (
    <div className="p-4 border border-secondary rounded-lg">
      <h2 className="text-xl font-bold text-accent mb-2">{title}</h2>
      <div className="text-gray-300">
        {children || 'This is an example component from a scaffold-xrp module.'}
      </div>
    </div>
  );
}

export default ExampleComponent;
